# Introduction: What you'll learn from this book

This book is written for scientists, data scientists, software developers, and others who use Python to do numeric computing or data processing.
Python[^cpython] is notoriously slow, and to handle large-scale data processing in a reasonable amount of time, the solution has traditionally involved writing Python extensions in a fast, low-level, compiled language: C, C++, Fortran, Cython, Numba, Rust, and others.

Sometimes these fast, compiled extensions are shared libraries like NumPy, SciPy, Pandas, or Polars.
If those libraries work for you, no need to read the rest of this book!

Sometimes, however, pre-existing libraries aren't fast enough, or aren't memory efficient enough, or most commonly of all simply don't implement the algorithms you need.
In that case, you will need to write your own code in a low-level language.

## Fast software requires you to do some work

* Switching to compiled language helps, but isn't magic, so can be disappointing if it doesn't help as much as you'd hoped
* But there's actually a lot you can do
   * Generic optimization, which applies to any programming language
       * Algorithm choice, `O()` as scalability
       * Reducing the constant for a specific algorithm
   * Once you switch to compiled low-level language:
      * Compilers can do generic optimization for you... up to a point. so it helps to understand what they can or can't do
      * Python's overhead stops being a bottleneck. that means you need a more realistic model of how the CPU and memory work to get faster software


[^cpython]: Technically, it's not the language that's slow, it's the default implementation. To distinguish the two, the Python interpreter is often known as CPython. The PyPy interpreter is a different implementation of the language that can do math much faster, but it adds overhead when interoperating with NumPy and other similar libraries, and lags behind on language features.

TODO

* who this is for
* what you'll get out of it
* what it's not about (Numba)
* quick overview of chapters
