project:
  type: book

book:
  title: "Speed up your Python data processing code with a low-level compiled language"
  author: "Itamar Turner-Trauring"
  date: "7/26/2023"
  chapters:
    - index.qmd
    - part: part_1/00.qmd  # General performance
      chapters:
        - part_1/01_algorithms.qmd
        - part_1/02_generic_optimization.qmd
        - part_1/03_customize_for_your_data.qmd
    - part: part_2/00.qmd  # Compiler optimizations
      chapters:
        - part_2/01_compiler_optimizations.qmd
        - part_2/02_aliasing.qmd
        - part_2/03_bulk_objects.qmd
        - part_2/04_undefined_behavior.qmd
        - part_2/05_writing_for_the_compiler.qmd
    - part: part_3/00.qmd  # Modern CPUs parallelism
      chapters:
        - part_3/01_instruction_level_parallelism.qmd
        - part_3/02_simd.qmd
        - part_3/03_more_about_simd.qmd
    - part: part_4/00.qmd  # Branches
      chapters:
        - part_4/01_avoid_branches.qmd
        - part_4/02_branchless.qmd
        - part_4/03_edge_case_branches.qmd
        - part_4/04_bounds_checking.qmd
        - part_4/05_divide_by_zero.qmd
    - part: part_5/00.qmd  # Floating point
      chapters:
        - part_5/01_manual_optimization.qmd
        - part_5/02_using_integers_instead.qmd
        - part_5/03_fast_math.qmd
    - part: part_6/00.qmd  # CPU memory cache
      chapters:
        - part_6/01_fit_in_cache.qmd
        - part_6/02_linear_scan.qmd
        - part_6/03_smaller_data_types.qmd
        - part_6/04_n_dimensional.qmd
        - part_6/05_learn_implementation_details.qmd
    - part: "More examples"
      chapters:
        - part_7/01_example_rescale_contrast.qmd
        - part_7/02_example_dithering.qmd
        - part_7/03_example_memory_layout.qmd
    # conclusion.qmd: more things you can learn? assembly, alignment (https://www.bazhenov.me/posts/2024-02-performance-roulette/), cost of loading the code, more detailed CPU-specific architecture like µops, and much more
  appendices:
    - appendices/01_when.qmd
    - appendices/02_prerequisites.qmd
    - appendices/03_microbenchmarking.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  cache: true


