project:
  type: book

book:
  title: "Speed up your Python data processing code with a low-level compiled language"
  author: "Itamar Turner-Trauring"
  date: "7/26/2023"
  chapters:
    - index.qmd
    - 001_introduction.qmd
    - 002_prerequisites.qmd
    - part: part_1.qmd  # General performance
      chapters:
        - 01_algorithms.qmd
        - 03_generic_optimization.qmd
        - 09_trading_accuracy_for_speed.qmd
    - part: part_2.qmd
      chapters:
        - 02_low_level_compilation.qmd
        - 04_the_compiler_optimizes_for_you.qmd
        - aliasing.qmd
        - external_memory.qmd
    - part: "TODO more sophisticated mental model of CPU"
      chapters:
        - more_compiler_optimizations.qmd
        - 04_instruction_level_parallelism.qmd
        - 05_simd.qmd
        - getting_rid_of_branches.qmd
        - 06_memory_heirarchy.qmd
    - 07_floating_point.qmd
    - 08_integers.qmd
    - 10_undefined_behavior.qmd
    - 11_example_rescale_contrast.qmd
    - 12_example_dithering.qmd
    - 13_example_memory_layout.qmd
  appendices:
    - 01_when.qmd
    - 14_microbenchmarking.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  cache: true


