project:
  type: book

book:
  title: "Speed up your Python data processing code with a low-level compiled language"
  author: "Itamar Turner-Trauring"
  date: "7/26/2023"
  chapters:
    - index.qmd
    - 001_introduction.qmd
    - part: part_1/00.qmd  # General performance
      chapters:
        - part_1/01_algorithms.qmd
        - part_1/02_generic_optimization.qmd
        - part_1/03_trading_accuracy_for_speed.qmd
    - part: part_2/00.qmd
      chapters:
        - part_2/01_low_level_compilation.qmd
        - part_2/02_compiler_optimizations.qmd
        - part_2/03_aliasing.qmd
    - part: part_3/00.qmd
      chapters:
        - part_3/01_instruction_level_parallelism.qmd
        - part_3/02_simd.qmd
        - part_3/03_getting_rid_of_branches.qmd
        #- complex_branches.qmd  may be a dead end
        - part_3/04_hidden_branching.qmd
        - part_3/05_more_compiler_optimizations.qmd
    - part: part_4/00.qmd
      chapters: # manual optimization, using integers instead, fast math plus crt mess
    - part: part_5/00.qmd
      chapters:
        - part_5/01_fit_in_cache.qmd
        - part_5/02_linear_scan.qmd
        - part_5/03_smaller_data_types.qmd
        - part_5/04_n_dimensional.qmd
        # non-contiguous views' impact on compiler?
    - part: part_6/00.qmd
      chapters:
        - part_6/01_more_about_simd.qmd
    - part: "More examples"
      chapters:
        - 01_example_rescale_contrast.qmd
        - 02_example_dithering.qmd
        - 03_example_memory_layout.qmd
        - 04_example_branchless.qmd
    - 07_floating_point.qmd
    - 08_integers.qmd
    - 10_undefined_behavior.qmd
  appendices:
    - 01_when.qmd
    - 002_prerequisites.qmd
    - 14_microbenchmarking.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  cache: true


