project:
  type: book

book:
  title: "Practices of Performance"
  subtitle: "Speeding up computational Python"
  author: "Itamar Turner-Trauring"
  date: "7/1/2025"
  chapters:
    - index.qmd
    - 010_introduction.qmd
    - 020_profiler.qmd
    - part: "The Practice of Efficiency"
      chapters:
        - part_1_efficiency/010_vectorized_operations.qmd
        - part_1_efficiency/030_algorithms.qmd
        - part_1_efficiency/040_generic_optimization.qmd
        - part_1_efficiency/050_lookup_table.qmd
        - part_1_efficiency/060_example_median_threshold.qmd
        - part_1_efficiency/070_edge_case_branches.qmd
        #- part_1_efficiency/07_research.qmd - mention Huang, DP algorithm
    - part: "The Pratice of Compilation"
      chapters:
        - part_2_compilation/000.qmd
        - part_2_compilation/010_compiler_optimizations.qmd
        - part_2_compilation/020_memory_allocation.qmd
        - part_2_compilation/030_aliasing.qmd
        - part_2_compilation/040_reducing_type_conversions.qmd
        - part_2_compilation/050_floating_point.qmd
        - part_2_compilation/060_manual_optimization.qmd
        - part_2_compilation/070_fast_math.qmd
        - part_2_compilation/080_bounds_checking.qmd
        - part_2_compilation/090_bounds_checking_auto_removal.qmd
        - part_2_compilation/100_divide_by_zero.qmd
        - part_2_compilation/110_undefined_behavior.qmd
        - part_2_compilation/120_overflow.qmd
        - part_2_compilation/130_hardware_differences.qmd
    - part: "The Pratice of Mechanical Sympathy"
      chapters:
        - part_3_mechanical_sympathy/000.qmd
        - part_3_mechanical_sympathy/010_instruction_level_parallelism.qmd
        - part_3_mechanical_sympathy/020_simd.qmd
        - part_3_mechanical_sympathy/030_more_about_simd.qmd
        - part_3_mechanical_sympathy/040_avoid_branches.qmd
        - part_3_mechanical_sympathy/050_branchless.qmd
        - part_3_mechanical_sympathy/060_memory.qmd
        - part_3_mechanical_sympathy/070_linear_scan.qmd
        - part_3_mechanical_sympathy/080_learn_implementation_details.qmd
        - part_3_mechanical_sympathy/090_n_dimensional.qmd
        - part_3_mechanical_sympathy/100_example_memory_layout.qmd
    - part: "The Practice of Process"
      chapters:
        - part_4_process/010_choosing_a_programming_language.qmd
        - part_4_process/020_bulk_objects.qmd
        - part_4_process/030_microbenchmarking.qmd
        - part_4_process/040_dont_break_your_code.qmd
        - part_4_process/050_document_your_code.qmd
        # optimization first, parallelism later
        # - part_4_process/060_keep_code_from_getting_slower.qmd
        - part_4_process/070_next_steps.qmd
  appendices:
    - appendices/01_prerequisites.qmd
#    - references.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  cache: true
